// GENERATED by scripts/build-photo-index.js. Do not edit; re-run "npm run build:photos".
export const photos: Record<string, number> = {
  'ars-electronica.jpg': require('../../../data/photos/ars-electronica.jpg'),
  'grottenbahn.jpg': require('../../../data/photos/grottenbahn.jpg'),
  'lentos.jpg': require('../../../data/photos/lentos.jpg'),
  'mariendom.jpg': require('../../../data/photos/mariendom.jpg'),
  'pestsaeule.jpg': require('../../../data/photos/pestsaeule.jpg'),
  'poestlingberg.jpg': require('../../../data/photos/poestlingberg.jpg'),
};
